CREATE DATABASE LAB7_13_4_PH28706
IF OBJECT_ID('MATHANG') IS NOT NULL 
DROP TABLE MATHANG
CREATE TABLE MATHANG(
    MAHANG CHAR(10),
    TENHANG NVARCHAR(50),
    DONGIA INT,
    PRIMARY KEY (MAHANG)
);

IF OBJECT_ID('KHACHHANG') IS NOT NULL
DROP TABLE KHACHHANG
CREATE TABLE KHACHHANG(
    MAKH CHAR(10),
    TENKH NVARCHAR(50),
    NGAYSINH DATE,
    GIOITINH NVARCHAR(10),
    QUEQUAN NVARCHAR(50),
    PRIMARY KEY (MAKH)
);
IF OBJECT_ID('HOADON') IS NOT NULL
DROP TABLE HOADON
CREATE TABLE HOADON(
    SOPHIEU CHAR(10),
    MAKH CHAR(10),
    NGAYLAP DATE,
    PRIMARY KEY (SOPHIEU),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);
IF OBJECT_ID('CTHOADON') IS NOT NULL
DROP TABLE CTHOADON
CREATE TABLE CTHOADON(
    SOPHIEU CHAR(10),
    MAHANG CHAR(10),
    SOLUONG INT,
    PRIMARY KEY (SOPHIEU,MAHANG),
    FOREIGN KEY (SOPHIEU) REFERENCES HOADON(SOPHIEU),
    FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG)
);
INSERT INTO MATHANG(MAHANG, TENHANG, DONGIA) VALUES
('M1', N'DƯỠNG MÔI OHUI', 200000),
('M2', N'TINH CHẤT OHUI', 1000000),
('M3', N'KEM DƯỠNG OHUI', 550000);
INSERT INTO KHACHHANG(MAKH, TENKH, GIOITINH, NGAYSINH, QUEQUAN) VALUES
('K1', N'TRẦN TRIỆU VY', N'NỮ', '2000/12/01', N'HÀ NỘI'),
('K2', N'TRẦN ĐÌNH TRỌNG', N'NAM', '2006/03/02', N'THÁI BÌNH'),
('K3', N'MINH HÀ', N'NỮ', '2013/03/14', N'SÀI GÒN'),
('K4', N'TRẦN THỊ THU PHƯƠNG', N'NỮ', '2003/08/09', N'THANH HOÁ');
INSERT INTO HOADON(MAKH, SOPHIEU,NGAYLAP) VALUES
('K1', 'P1', '2022/01/01'),
('K1', 'P2', '2022/01/18'),
('K3', 'P3', '2022/04/18');
INSERT INTO CTHOADON(MAHANG, SOLUONG, SOPHIEU) VALUES
('M1', 2, 'P1'),
('M2', 3, 'P1'),
('M2', 1, 'P2'),
('M3', 2, 'P1');

--Câu 2: Truy Vấn dữ liệu SQL (5đ)
--a.	Đưa ra thông tin: Makh, Tenkh, Gioitinh của những khách hàng có Họ Trần và Quequan là ‘Hà Nội’. (0.5đ). 
SELECT * FROM KHACHHANG WHERE TENKH LIKE N'TRẦN %' AND QUEQUAN LIKE N'%HÀ NỘI%'
--b.	Đưa ra thông tin các khách hàng > 20 tuổi. (0.5đ). 
SELECT *, YEAR(GETDATE())-YEAR(NGAYSINH) AS N'TUỔI' FROM KHACHHANG WHERE YEAR(GETDATE())-YEAR(NGAYSINH)>20;
--c.	*Đưa ra thông tin danh sách các khách hàng (Makh, Tenkh, tổng tiền) có tổng thành tiền của các hóa đơn từ 1.000.
SELECT KH.MAKH,TENKH,SUM(CTHD.SOLUONG*MH.DONGIA) AS 'TỔNG TIỀN' FROM KHACHHANG AS KH JOIN HOADON AS HD
ON KH.MAKH=HD.MAKH
JOIN CTHOADON AS CTHD ON HD.SOPHIEU=CTHD.SOPHIEU
JOIN MATHANG AS MH ON CTHD.MAHANG=MH.MAHANG
GROUP BY hd.SOPHIEU,kh.MAKH,TENKH HAVING SUM(CTHD.SOLUONG*MH.DONGIA) >1000000
--d.      *Cho biết thông tin khách hàng chưa đặt đơn hàng nào. Thông tin gồm: Makh,Tenkh (1đ)
UPDATE KHACHHANG SET QUEQUAN = N'MIỀN TÂY' WHERE TENKH LIKE 'MINH HÀ'
--e.	Liệt kê thông tin: Makh, Tenkh, Mahang, Tenhang, Dongia, Soluong của khách hàng có tên khách hàng là Trần Triệu Vy . sắp xếp giảm dần theo ngay mua hàng (1đ)
SELECT KH.MAKH,TENKH,MH.MAHANG,TENHANG,DONGIA,CTHD.SOLUONG FROM KHACHHANG AS KH JOIN HOADON AS HD ON KH.MAKH=HD.MAKH
JOIN CTHOADON AS CTHD ON HD.SOPHIEU=CTHD.SOPHIEU
JOIN MATHANG AS MH ON CTHD.MAHANG=MH.MAHANG
WHERE TENKH  LIKE N'TRẦN TRIỆU VY'
--f.	Đưa ra thông tin các khách đã mua hàng trong tháng 1/2022 (1đ).XEP GIAM DAN THEO NGAY LAP HOA DON
SELECT KH.*, HD.NGAYLAP FROM KHACHHANG KH
JOIN HOADON HD ON KH.MAKH=HD.MAKH WHERE YEAR(HD.NGAYLAP)=2022 AND MONTH(HD.NGAYLAP)=1 ORDER BY HD.NGAYLAP DESC
--WHERE HD.NGAYLAP LIKE '2022/01/%'
--Câu 3. Hãy viết lệnh SQL thực hiện các thao tác sau: (2đ)
--a.	Thêm một bản ghi mới vào chitiethoadon,dữ liệu phù hợp( không được nhập giá trị null). (0.5đ)
INSERT INTO CTHOADON(SOPHIEU,MAHANG,SOLUONG) VALUES
('P3','M1',3)
--b.	Thay đổi quê quán của khách hàng Minh Hà thành ‘Miền Tây’ (1đ)
UPDATE KHACHHANG SET QUEQUAN = N'MIỀN TÂY' WHERE TENKH LIKE 'MINH HÀ'
--c.	 Xóa mặt hàng có tên hàng ‘Kem dưỡng Ohui’ (0.5đ)
UPDATE KHACHHANG SET QUEQUAN = N'MIỀN TÂY' WHERE TENKH LIKE 'MINH HÀ'
