CREATE DATABASE RESTAURANT

IF OBJECT_ID('ORDERS') IS NOT NULL
DROP TABLE ORDERS
CREATE TABLE ORDERS(
    ORDERID INT,
    CUSTOMERID INT,
    ORDERDATE DATETIME,

);

IF OBJECT_ID('CUSTOMERS') IS NOT NULL
DROP TABLE CUSTOMERS
CREATE TABLE CUSTOMERS(
    CUSTOMERID INT PRIMARY KEY,
    CUSTOMERNAME VARCHAR(20),
    CONTACTNAME VARCHAR(20),
    COUNTRY VARCHAR(20), 

);

ALTER TABLE CUSTOMERS
ADD  COUNTRYID INT;

ALTER TABLE CUSTOMERS
DROP COLUMN COUNTRY;

SELECT * FROM CUSTOMERS

UPDATE CUSTOMERS
SET COUNTRYID = 102
WHERE  CUSTOMERID = 1

UPDATE CUSTOMERS
SET COUNTRYID = 130
WHERE  CUSTOMERID = 2







IF OBJECT_ID('COUNTRY') IS NOT NULL
DROP TABLE COUNTRY
CREATE TABLE COUNTRY(
    COUNTRYID VARCHAR(30) PRIMARY KEY,
    COUNTRYNAME VARCHAR(30),

);
DROP TABLE COUNTRY

INSERT INTO COUNTRY(COUNTRYID,COUNTRYNAME) VALUES
('102','VIET NAM'),
('103', 'MY');
SELECT * FROM COUNTRY




INSERT INTO ORDERS(ORDERID,CUSTOMERID,ORDERDATE) VALUES
('10308','2','1996/09/18'),
('10309','37','1996/09/19'),
('10310','77','1996/09/20');

SELECT * FROM ORDERS;


INSERT INTO ORDERS(ORDERID,CUSTOMERID,ORDERDATE) VALUES
('10311','2','2022/08/07');

DROP TABLE ORDERS;






ALTER TABLE ORDERS
ADD ORDERSSTATUS VARCHAR(30);


ALTER TABLE ORDERS
ADD COUNTRY VARCHAR(30);


ALTER TABLE ORDERS
ADD CUSTOMERNAME VARCHAR(30);


UPDATE ORDERS 
SET ORDERSSTATUS = 'THANH CONG'
WHERE ORDERID = 10308


INSERT INTO CUSTOMERS(CUSTOMERID,CUSTOMERNAME,CONTACTNAME,COUNTRY) VALUES
('1','PHAM THI YEN','PTY','VIET NAM'),
('2','NGUYEN THI ANH','NTA','VIET NAM');
SELECT * FROM CUSTOMERS;


ALTER TABLE CUSTOMERS
ADD COUNTRYID INT

ALTER TABLE CUSTOMERS
DROP COLUMN COUNTRY


UPDATE CUSTOMERS
SET COUNTRYID = 102
WHERE CUSTOMERID = 1

UPDATE CUSTOMERS
SET COUNTRYID = 103
WHERE CUSTOMERID = 2


ALTER TABLE ORDERS
ADD PAYMENTTYPE VARCHAR(30)

SELECT * FROM ORDERS

ALTER TABLE ORDERS
DROP  COLUMN COUNTRY 

ALTER TABLE ORDERS
DROP COLUMN PAYMENTTYPE




/* CAP NHAT DON HANG 10308 THANH TRANG THAI THANH CONG VA LOAI THANH TOAN LA CHUYEN KHOAN */

UPDATE ORDERS
SET ORDERSSTATUS = 'THANH CONG', PAYMENTTYPE = 'CHUYEN KHOAN'
WHERE ORDERID = '10308'









UPDATE ORDERS
SET ORDERSSTATUS = 'THANH CONG' , PAYMENTTYPE = 'CHUYEN KHOAN'
WHERE ORDERID = 10308;

UPDATE ORDERS
SET ORDERSSTATUS = 'THANH CONG', PAYMENTTYPE = ' TIEM MAT'
WHERE ORDERID = 10309;

UPDATE ORDERS
SET ORDERSSTATUS = ' KHONG THANH CONG' , PAYMENTTYPE ='CHUYEN KHOAN'
WHERE ORDERID = 10310


UPDATE ORDERS
SET ORDERSSTATUS = 'THANH CONG', PAYMENTTYPE = 'TIEN MAT'
WHERE ORDERID = 10311
 

SELECT ORDERS.ORDERID, ORDERS.ORDERSSTATUS,CUSTOMERS.CUSTOMERNAME,CUSTOMERS.CONTACTNAME,COUNTRY.COUNTRYNAME
FROM CUSTOMERS 
JOIN ORDERS ON ORDERS.CUSTOMERID = CUSTOMERS.CUSTOMERID
JOIN COUNTRY ON CUSTOMERS.COUNTRYID = COUNTRY.COUNTRYID;



