CREATE DATABASE QUANLYDETAI
IF OBJECT_ID('GIAOVIEN') IS NOT NULL
DROP TABLE GIAOVIEN
CREATE TABLE GIAOVIEN(
    MAGV VARCHAR(50) PRIMARY KEY,
    HOTEN NVARCHAR(50),
    NGAYSINH DATE,
    QUEUQUAN NVARCHAR(50),
    GIOITINH NVARCHAR(50),

);

IF OBJECT_ID('DETAI') IS NOT NULL
DROP TABLE DETAI
CREATE TABLE DETAI(
    MADT VARCHAR(50) ,
    TENDT NVARCHAR(50),
    NAMTHEHIEN DATE,
    MAGV VARCHAR(50),
    PRIMARY KEY (MADT),
    FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV),

);

IF OBJECT_ID('SINHVIEN') IS NOT NULL
DROP TABLE SINHVIEN
CREATE TABLE SINHVIEN(
    MASV VARCHAR(50),
    HOTEN NVARCHAR(50),
    NGAYSINHSV DATE,
    QUEQUANSV NVARCHAR(50),
    DIEM INT,
    MADT VARCHAR(50),
    PRIMARY KEY(MADT,MASV),

    FOREIGN KEY (MADT) REFERENCES DETAI(MADT),

);

INSERT INTO GIAOVIEN(MAGV,HOTEN,NGAYSINH,QUEUQUAN,GIOITINH) VALUES
('GV01',N'TRẦN THỊ LOAN','1978/05/06',N'NAM ĐỊNH',N'NỮ'),
('GV02',N'LÊ VIẾT THỊNH','1989/03/05',N'HÀ TĨNH',N'NAM'),
('GV03',N'TRẦN HỮU THUẬN','1991/01/09',N'HÀ NỘI',N'NAM'),

---CAU6
('GV04',N'TRẦN CÔNG LÔNG','1999/01/20',N'HIỆP HOÀ',N'NAM');
SELECT * FROM GIAOVIEN



INSERT INTO DETAI(MADT,TENDT,NAMTHEHIEN,MAGV )VALUES
('D01',N'CÔNG NGHỆ 4.0','2017','GV01'),
('D02',N'CÔNG NGHỆ BLOCKCHAIN','2018','GV03'),
('D03',N'BITCOIN','2018','GV03');
DELETE FROM DETAI
SELECT * FROM DETAI

INSERT INTO SINHVIEN(MASV,HOTEN,NGAYSINHSV,QUEQUANSV,DIEM,MADT) VALUES
('S001',N'LÊ QUANG TÈO','2000/01/01',N'HÀ NỘI',7,'D02'),
('S002',N'ĐỖ MỸ LỊNH','1998/08/05',N'HÀ TĨNH',10,'D01'),
('S003',N'MAI PHƯƠNG THUÝ','1999/09/06',N'NGHỆ AN',8,'D02');
SELECT * FROM SINHVIEN
DELETE FROM SINHVIEN

-- CAU2
SELECT MASV, GIAOVIEN.HOTEN, TENDT FROM SINHVIEN JOIN DETAI ON SINHVIEN.MADT = DETAI.MADT
JOIN GIAOVIEN ON GIAOVIEN.MAGV = DETAI.MAGV
WHERE GIAOVIEN.HOTEN = N'TRẦN THỊ LOAN'
GROUP BY  MASV, GIAOVIEN.HOTEN, TENDT

--CAU3
SELECT MASV,SINHVIEN.HOTEN,YEAR(GETDATE())-YEAR(NGAYSINHSV) TUOI FROM SINHVIEN
WHERE QUEQUANSV = N'HÀ NỘI' AND YEAR(GETDATE())-YEAR(NGAYSINHSV)> 18

--CAU4
SELECT GIAOVIEN.MAGV,GIAOVIEN.HOTEN,MADT FROM GIAOVIEN JOIN DETAI ON DETAI.MAGV = GIAOVIEN.MAGV



--CAU7
UPDATE GIAOVIEN
SET QUEUQUAN = N'HÀ NỘI'
WHERE GIAOVIEN.HOTEN = N'TRẦN THỊ LOAN'
SELECT * FROM GIAOVIEN

--- CAU8
SELECT * FROM SINHVIEN JOIN DETAI ON SINHVIEN.MADT = DETAI.MADT
WHERE MADT NOT IN
(SELECT MADT FROM DETAI)





