CREATE DATABASE ONTHI1

IF OBJECT_ID('SINHVIEN') IS NOT NULL
DROP TABLE SINHVIEN
CREATE TABLE SINHVIEN(
    MASV VARCHAR(50) PRIMARY KEY,
    MAMON VARCHAR(50),
    DIEM FLOAT,
);


IF OBJECT_ID('THONGTIN') IS NOT NULL
DROP TABLE THONGTIN
CREATE TABLE THONGTIN(
   MASV VARCHAR(50),
   HODEM NVARCHAR(50),
   TEN NVARCHAR(50),
   NGAYSINH DATE,
   MALOP VARCHAR(50) PRIMARY KEY,

   FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
);

INSERT INTO SINHVIEN(MASV,MAMON,DIEM) VALUES
('SV01','M01',8.7),

('SV02','M01',4.5),

('SV03','M01',3.5);
SELECT * FROM SINHVIEN

INSERT INTO THONGTIN(MASV,HODEM,TEN,NGAYSINH,MALOP) VALUES
('SV01',N'LÊ ANH',N'HẢI','2000/12/03','L01'),
('SV02',N'PHẠM THỊ',N'HƯƠNG','2002/08/06','L03'),
('SV03',N'PHẠM THU',N'LAN','2001/03/25','L02');
SELECT * FROM THONGTIN


