CREATE DATABASE ONTAPLAB7
IF OBJECT_ID('MATHANG') IS NOT NULL
DROP TABLE MATHANG
CREATE TABLE MATHANG(
    MAHANG VARCHAR(30) PRIMARY KEY,
    TENHANG NVARCHAR(50),
    DONGIA VARCHAR(30),
 

);

IF OBJECT_ID('KHACHHANG') IS NOT NULL
DROP TABLE KHANHHANG
CREATE TABLE KHANHHANG(
    MAKH VARCHAR (40) PRIMARY KEY,
    TENKH NVARCHAR(30),
    NGAYSINH DATETIME,
    GIOITINH NVARCHAR(50),
    QUEQUAN NVARCHAR(50),

);

IF OBJECT_ID('HOADON') IS NOT NULL
DROP TABLE HOADON
CREATE TABLE HOADON(
    SOPHIEU VARCHAR(30) PRIMARY KEY,
    NGAYLAP DATETIME,
    MAKH VARCHAR (40),
    
FOREIGN KEY (MAKH) REFERENCES KHANHHANG(MAKH),


);

IF OBJECT_ID('CTHOADON') IS NOT NULL
DROP TABLE CTHOADON
CREATE TABLE CTHOADON(
    SOPHIEU VARCHAR(30),
    MAHANG VARCHAR(30),
    SOLUONG INT,

    PRIMARY KEY(SOPHIEU,MAHANG),

    FOREIGN KEY (SOPHIEU) REFERENCES HOADON(SOPHIEU),
    FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG),

    
);

INSERT INTO MATHANG(MAHANG,TENHANG,DONGIA) VALUES
('M1',N'DƯỠNG MÔI OHUI','200000'),
('M2',N'TINH CHẤT OHUI','1000000'),
('M3',N'KEM DƯỠNG OHUI','550000');
SELECT * FROM MATHANG


INSERT INTO KHANHHANG(MAKH,TENKH,NGAYSINH,GIOITINH,QUEQUAN) VALUES
('K1',N'TRẦN TRIỆU VY','2000/12/01',N'NỮ',N'HÀ NỘI'),
('K2',N'TRẦN ĐÌNH TRỌNG','2006/03/02',N'NAM',N'THÁI BÌNH'),
('K3',N'MINH HÀ','2013/03/14',N'NỮ',N'SÀI GÒN');
SELECT * FROM KHANHHANG

INSERT INTO HOADON(SOPHIEU,NGAYLAP,MAKH) VALUES
('P1','2022/01/01','K1'),
('P2','2022/01/18','K1'),
('P3','2022/04/18','K3');
SELECT * FROM HOADON

INSERT INTO CTHOADON(SOPHIEU,MAHANG,SOLUONG) VALUES
('P1','M1',2),
('P1','M2',3);