CREATE DATABASE ONDETH1

IF OBJECT_ID('MATHANG') IS NOT NULL
DROP TABLE MATHANG
CREATE TABLE MATHANG(
    MSMH VARCHAR(50) PRIMARY KEY,
    TENHANG NVARCHAR(50),
    DONGIA INT,
    DVT NVARCHAR(50),
);

IF OBJECT_ID('KHACHHANG') IS NOT NULL
DROP TABLE KHACHHANG
CREATE TABLE KHACHHANG(
    MAKH VARCHAR(50)PRIMARY KEY,
    TENKH NVARCHAR(50),
    DIACHI NVARCHAR(50),
);

IF OBJECT_ID('PHIEUNHAP') IS NOT NULL
DROP TABLE PHIEUNHAP
CREATE TABLE PHIEUNHAP(
   SOPN INT PRIMARY KEY,
   NGAYLAP DATE,
   MAKH VARCHAR(50),
   KHO VARCHAR(50),

   FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
);



IF OBJECT_ID('CHITIETNHAP') IS NOT NULL
DROP TABLE CHITIETNHAP
CREATE TABLE CHITIETNHAP(
  SOPN INT,
  MSMH VARCHAR(50),
  SOLUONG INT,
  PRIMARY KEY(SOPN,MSMH),

  FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP(SOPN),
  FOREIGN KEY (MSMH) REFERENCES MATHANG(MSMH),
);

INSERT INTO MATHANG(MSMH,TENHANG,DONGIA,DVT) VALUES
('1',N'BÁNH','102',N'ĐỒNG'),
('2',N'NƯỚC','103',N'ĐÔ LA'),
('3',N'KẸO','104',N'TRĂM');
SELECT * FROM MATHANG

INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI) VALUES
('KH01',N'NGỌC ANH',N'BẮC GIANG'),
('KH02',N'ÁNH DƯƠNG',N'HÀ NỘI'),
('KH03',N'HÀO ANH',N'HIỆP HOÀ');
SELECT * FROM KHACHHANG


INSERT INTO PHIEUNHAP(SOPN,NGAYLAP,MAKH,KHO) VALUES
(2,'2021/12/10','KH01','KH1'),
(4,'2023/10/09','KH02','KH2'),
(8,'2022/03/20','KH03','KH3');
SELECT * FROM PHIEUNHAP
DELETE FROM PHIEUNHAP

INSERT INTO PHIEUNHAP(SOPN,NGAYLAP,MAKH,KHO) VALUES
(5,'2023/11/02','KH04','KH4');


INSERT INTO CHITIETNHAP(SOPN,MSMH,SOLUONG) VALUES
(2,'1',3),
(4,'2',8),
(8,'3',9);
SELECT * FROM CHITIETNHAP
DELETE FROM CHITIETNHAP



----CAU1
SELECT PHIEUNHAP.SOPN,TENKH,NGAYLAP,SUM(DONGIA * SOLUONG) THANHTIEN FROM PHIEUNHAP 
JOIN KHACHHANG ON PHIEUNHAP.MAKH = KHACHHANG.MAKH
JOIN CHITIETNHAP ON CHITIETNHAP.SOPN = PHIEUNHAP.SOPN
JOIN MATHANG ON CHITIETNHAP.MSMH = MATHANG.MSMH
GROUP BY PHIEUNHAP.SOPN,TENKH,NGAYLAP

----CAU1.1
SELECT PHIEUNHAP.SOPN,TENKH,NGAYLAP,SUM(DONGIA* SOLUONG) 'THÀNH TIỀN' FROM PHIEUNHAP 
JOIN KHACHHANG ON PHIEUNHAP.MAKH = KHACHHANG.MAKH
JOIN CHITIETNHAP ON PHIEUNHAP.SOPN = PHIEUNHAP.SOPN
JOIN MATHANG ON MATHANG.MSMH = CHITIETNHAP.MSMH
GROUP BY PHIEUNHAP.SOPN,TENKH,NGAYLAP

---CÂU 2
SELECT TENKH,MONTH(NGAYLAP) MONTH ,YEAR(NGAYLAP) YEAR,SUM(SOLUONG) TONG FROM KHACHHANG JOIN PHIEUNHAP ON  KHACHHANG.MAKH = PHIEUNHAP.MAKH
JOIN CHITIETNHAP ON CHITIETNHAP.SOPN = PHIEUNHAP.SOPN
WHERE TENKH = N'NGỌC ANH' AND MONTH(NGAYLAP) = '12' AND YEAR(NGAYLAP) = '2021'
GROUP BY TENKH,NGAYLAP

----CÂU 3
SELECT TENKH, KHACHHANG.MAKH, SUM(SOLUONG * DONGIA) 'TỔNG TIỀN'FROM KHACHHANG JOIN PHIEUNHAP ON KHACHHANG.MAKH = PHIEUNHAP.MAKH
JOIN CHITIETNHAP ON CHITIETNHAP.SOPN = PHIEUNHAP.SOPN
JOIN MATHANG ON MATHANG.MSMH = CHITIETNHAP.MSMH
GROUP BY TENKH,KHACHHANG.MAKH
HAVING SUM(SOLUONG * DONGIA) > 800


----CÂU4
SELECT KHACHHANG.MAKH,TENKH,SOLUONG,CHITIETNHAP.MSMH,SOLUONG,DONGIA FROM KHACHHANG JOIN PHIEUNHAP ON KHACHHANG.MAKH = PHIEUNHAP.MAKH
JOIN CHITIETNHAP ON CHITIETNHAP.SOPN = PHIEUNHAP.SOPN
JOIN MATHANG ON MATHANG.MSMH = CHITIETNHAP.MSMH
WHERE TENKH = N'NGỌC ANH'
GROUP BY KHACHHANG.MAKH,TENKH,SOLUONG,CHITIETNHAP.MSMH,SOLUONG,DONGIA

----CÂU5
SELECT COUNT  KHACHH
FROM KHACHHANG


-----CÂU6
SELECT MAX(TONGSOPHIEU) TONGSP, MAKH FROM (SELECT COUNT(*) TONGSOPHIEU, MAKH
FROM PHIEUNHAP
GROUP BY MAKH) AS BANGTAM;











