CREATE DATABASE QUANLYDETAI3

IF OBJECT_ID('GIAOVIEN') IS NOT NULL
DROP TABLE GIAOVIEN
CREATE TABLE GIAOVIEN(
    MAGV VARCHAR(50) PRIMARY KEY,
    HOTEN NVARCHAR(50),
    NGAYSINH DATE,
    QUEQUAN NVARCHAR(50),
    GIOITINH NVARCHAR(50),

);
IF OBJECT_ID('DETAI') IS NOT NULL
DROP TABLE DETAI
CREATE TABLE DETAI(
    MADT VARCHAR(50) PRIMARY KEY,
    TENDT NVARCHAR(50),
    NAMTT DATE,
    MAGV VARCHAR(50),
    FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV),
    
);

IF OBJECT_ID('SINHVIEN') IS NOT NULL
DROP TABLE SINHVIEN
CREATE TABLE SINHVIEN(
    MASV VARCHAR(50) PRIMARY KEY,
    HOTENSV NVARCHAR(50),
    NGAYSINH DATE,
    QUEQUANSV NVARCHAR(50),
    DIEN INT,
    MADT VARCHAR(50),

    FOREIGN KEY (MADT) REFERENCES DETAI(MADT)
   
);

INSERT INTO GIAOVIEN(MAGV,HOTEN,NGAYSINH,QUEQUAN,GIOITINH) VALUES
('GV01',N'TRẦN THỊ LOAN','1978/05/06',N'NAM ĐỊNH',N'NỮ'),
('GV02',N'LÊ VIẾT THỊNH','1989/03/05',N'HÀ TĨNH',N'NAM'),
('GV03',N'TRẦN HỮU THIỆN','1991/01/09',N'HÀ NỘI',N'NAM');
SELECT * FROM GIAOVIEN

INSERT INTO DETAI(MADT,TENDT,NAMTT,MAGV) VALUES
('D01',N'CÔNG NGHỆ 4.0','2017','GV01'),
('D02',N'CÔNG NGHỆ BLOCKEHAIN','2018','GV03'),
('D03',N'BITCOIN','2018','GV03');
SELECT * FROM DETAI

INSERT INTO SINHVIEN(MASV,HOTENSV,NGAYSINH,QUEQUANSV,DIEN,MADT) VALUES
('S001',N'LÊ QUANG TÈO','2000/01/01',N'HÀ NỘI',7,'D02'),
('S002',N'ĐỖ MỸ LINH','1998/08/05',N'HÀ TĨNH',10,'D01'),
('S003',N'MAI PHƯƠNG THUÝ','1999/09/06',N'NGHỆ AN',10,'D02');
SELECT * FROM SINHVIEN


--CAU2
SELECT MASV,HOTENSV,TENDT FROM SINHVIEN 
JOIN DETAI ON SINHVIEN.MADT = DETAI.MADT
JOIN GIAOVIEN ON GIAOVIEN.MAGV = DETAI.MAGV
WHERE HOTEN = N'TRẦN THỊ LOAN'

---CAU3
SELECT MASV,HOTENSV,YEAR(GETDATE()) - YEAR(NGAYSINH) TUOI FROM SINHVIEN 
WHERE YEAR(GETDATE()) - YEAR(NGAYSINH) >= 18

---CAU4
SELECT GIAOVIEN.MAGV,HOTEN,COUNT(DETAI.MADT) DETAI FROM GIAOVIEN 
JOIN DETAI ON DETAI.MAGV = GIAOVIEN.MAGV
GROUP BY GIAOVIEN.MAGV,HOTEN
HAVING COUNT(DETAI.MADT) >= ALL(SELECT COUNT(DETAI.MADT)  FROM DETAI GROUP BY MAGV);

---CAU5
SELECT DETAI.MADT,TENDT,AVG(DIEN) DIEMTB FROM DETAI
 JOIN SINHVIEN ON DETAI.MADT = SINHVIEN.MADT
 GROUP BY  DETAI.MADT,TENDT

 --CAU7
 UPDATE GIAOVIEN
 SET QUEQUAN = N'HÀ NỘI'
 WHERE HOTEN = N'TRẦN THỊ LOAN'

 --CAU8

DELETE FROM DETAI
WHERE MADT NOT IN
 (SELECT MADT FROM SINHVIEN)
SELECT * FROM DETAI

--CAU8
DELETE FROM DETAI
WHERE MADT NOT IN
(SELECT MADT FROM SINHVIEN)

--CAU5
SELECT DETAI.MADT,TENDT,AVG(DIEN) FROM SINHVIEN 
JOIN DETAI ON DETAI.MADT = SINHVIEN.MADT
GROUP BY DETAI.MADT,TENDT
---CAU8
DELETE DETAI
WHERE MADT NOT IN
(SELECT MADT FROM SINHVIEN)