CREATE DATABASE QUANLYSINHVIEN

IF OBJECT_ID('GIAOVIEN') IS NOT NULL
DROP TABLE GIAOVIEN
CREATE TABLE GIAOVIEN(
    TENGV NVARCHAR(30),
    SDT INT,
    DIACHI NVARCHAR(30),
    IDGV INT,

);
DROP TABLE GIAOVIEN

INSERT INTO GIAOVIEN(TENGV,SDT,DIACHI,IDGV) VALUES
(N'NGỌC MAI','0987123479',N'10 HẬU DỊCH','10'),
(N'BINH MINH','0969691630',N'162 HÀ DUY PHIÊN','12');
SELECT * FROM GIAOVIEN

IF OBJECT_ID('KHOA') IS NOT NULL
DROP TABLE KHOA
CREATE TABLE KHOA(
    MAKH VARCHAR(50) PRIMARY KEY,
    TENKH NVARCHAR(50),
    SLSV INT,
);

INSERT INTO KHOA(MAKH,TENKH,SLSV) VALUES
('LTMT',N'LẬP TRÌNH MÁY TÍNH','2'),
('TKDH',N'THIẾT KẾ ĐỒ HOẠ','3');
SELECT * FROM KHOA


ALTER TABLE KHOA
ADD DIACHI NVARCHAR(30);


ALTER TABLE KHOA
ADD SLGV INT;

UPDATE  KHOA 
SET SLGV = '2', DIACHI = ' PHÒNG 203'
WHERE MAKH = 'LTMT';

UPDATE  KHOA 
SET SLGV = '7', DIACHI = ' PHÒNG 208'
WHERE MAKH = 'TKDH';


ALTER TABLE KHOA
ADD IDGV INT

UPDATE KHOA
SET IDGV = '10'
WHERE MAKH = 'LTMT';

UPDATE KHOA
SET IDGV = '12'
WHERE MAKH = 'TKDH';




IF OBJECT_ID('SINHVIEN') IS NOT NULL
DROP TABLE SINHVIEN
CREATE TABLE SINHVIEN(
    TENSV NVARCHAR(50),
    GIOITINH NVARCHAR(50),
    NOISINH NVARCHAR(50),
    NGAYSINH DATETIME,
    MASV VARCHAR(50) PRIMARY KEY,
    MAKH NVARCHAR(50),
    HOSV NVARCHAR(50),
    HOCBONG MONEY,
    DIEMTB INT,

);
INSERT INTO SINHVIEN(HOSV,TENSV,GIOITINH,NOISINH,NGAYSINH,MASV,MAKH,HOCBONG,DIEMTB) VALUES
(N'PHẠM',N'YẾN',N'NỮ',N'BẮC GIANG','2003/09/12','PH29','LTMT','12900','8'),
(N'NGUYỄN',N'ANH',N'NAM',N'HIỆP HOÀ','2003/10/02','PH26','TKDH','12081','7');
SELECT * FROM SINHVIEN


SELECT KHOA.MAKH,KHOA.TENKH,KHOA.SLSV,SINHVIEN.HOSV,SINHVIEN.TENSV,SINHVIEN.NOISINH,SINHVIEN.MAKH,SINHVIEN.NGAYSINH,GIAOVIEN.TENGV
FROM SINHVIEN
JOIN KHOA ON KHOA.MAKH = SINHVIEN.MAKH
JOIN GIAOVIEN ON KHOA.IDGV = GIAOVIEN.IDGV;

IF OBJECT_ID('MONHOC') IS NOT NULL
DROP TABLE MONHOC
CREATE TABLE MONHOC(
    MAMH VARCHAR(50) PRIMARY KEY,
    TENMH NVARCHAR(50),
    SOTIET TINYINT,
);
INSERT INTO MONHOC(MAMH,TENMH,SOTIET) VALUES
('LT',N'LẬP TRÌNH MÁY TÍNH','2'),
('TK',N'THIẾT KẾ ĐỒ HOẠ','4');
SELECT * FROM MONHOC


IF OBJECT_ID('KETQUA') IS NOT NULL
DROP TABLE KETQUA
CREATE TABLE KETQUA(
    MASV VARCHAR(50),
    MAMH VARCHAR(50),
    LANTHI TINYINT,
    DIEMTHI NUMERIC,
    KETQUA NVARCHAR(50),

);
DELETE FROM KETQUA
INSERT INTO KETQUA(MASV,MAMH,LANTHI,DIEMTHI,KETQUA) VALUES
('PH29','LT',9,9,N'ĐẠT'),
('PH26','TK',4,2,N'KHÔNG ĐẠT');
SELECT * FROM KETQUA