CREATE DATABASE QUANLYTHUVIEN

IF OBJECT_ID('THUTHU') IS NOT NULL
DROP TABLE THUTHU
CREATE TABLE THUTHU(
    MATHUTHU VARCHAR(50) PRIMARY KEY,
    HOTEN NVARCHAR(50),
    CCCD VARCHAR(50),
    SDT VARCHAR(10),
    NGAYSINH DATETIME,
    NGUOIMUON NVARCHAR(50),

);

IF OBJECT_ID('NGUOIMUON') IS NOT NULL
DROP TABLE NGUOIMUON
CREATE TABLE NGUOIMUON(
    CCCD VARCHAR(50) PRIMARY KEY,
    HOTEN NVARCHAR(50),
    NGAYSINH DATETIME,
    SDT VARCHAR(20),
    NGHENGHIEP NVARCHAR(40),
    GIOITINH NVARCHAR(50),
    DIACHI NVARCHAR(50),

);
IF OBJECT_ID('PHIEUMUON') IS NOT NULL
DROP TABLE PHIEUMUON
CREATE TABLE PHIEUMUON(
    MASOPHIEU VARCHAR(20) PRIMARY KEY,
    NGAYMUON DATETIME,
    NGAYTRA DATETIME,
    MASACH VARCHAR(30),
    SOLUONG INT,
    GHICHU NVARCHAR(30),
    MANGUOIMUON,
    MATHUTHU
);

IF OBJECT_ID('SACHDUOCMUON') IS NOT NULL
DROP TABLE SACHDUOCMUON
CREATE TABLE SACHDUOCMUON(
    MASACH VARCHAR(30),
    SOLUONG INT,
    TRANGTHAISACH NVARCHAR(30),
    TENSACH NVARCHAR(30),
    XUATXU NVARCHAR(30),
    MATACGIA VARCHAR(30) PRIMARY KEY,
    NAMXUATBAN INT,
    GIATIEN INT,

);

IF OBJECT_ID('TACGIA') IS NOT NULL
DROP TABLE TACGIA
CREATE TABLE TACGIA(
    MATACGIA VARCHAR(30) PRIMARY KEY,
    HOTEN NVARCHAR(50),
    NGAYSINH DATETIME,
    NGAYMAT DATETIME,
    GIOITINH NVARCHAR(50),
    NOISINH NVARCHAR(40),
    QUEQUAN NVARCHAR(40),
);

INSERT INTO THUTHU(MATHUTHU,HOTEN,CCCD,SDT,NGAYSINH,NGUOIMUON) VALUES
('TT01',N'NGUYỄN VĂN ANH','12234','0987123789','2000/09/23',N'NGUYỄN VĂN HIẾU'),
('TT03',N'HOÀNG NGỌC YẾN','89293','0789234053','1996/12/01',N'PHẠM THỊ THẢO');

SELECT * FROM THUTHU
DELETE FROM THUTHU

INSERT INTO NGUOIMUON(CCCD,HOTEN,MASOPHIEU,NGAYSINH,SDT,NGHENGHIEP,GIOITINH,DIACHI) VALUES
('120926',N'NGUYỄN VĂN DUY','P01','2003/01/21','0802749026',N'SINHVIEN',N'NAM',N'HÀ NỘI'),
('792902',N'NGUYỄN HỒNG NGỌC','P02','2005/10/13','0120987652',N'SINHVIEN',N'NỮ',N'SƠN TÂY');
SELECT * FROM NGUOIMUON

INSERT INTO PHIEUMUON(MASOPHIEU,NGAYMUON,NGAYTRA,MASACH,SOLUONG,GHICHU) VALUES
('P01','2022/12/09','2022/12/20','PH29','2',N'KHÔNG CÓ GÌ'),
('P03','2022/10/10','2022/10/25','PH25','1',N'KHÁCH HÀNG THÂN THIẾT');
SELECT * FROM PHIEUMUON

INSERT INTO SACHDUOCMUON(MASACH,SOLUONG,TRANGTHAISACH,TENSACH,XUATXU,MATACGIA,NAMXUATBAN,GIATIEN) VALUES
('PH29','2',N'MỚI',N'BÚP SEN XANH',N'VIỆT NAM','TG01','2020','80'),
('PH25','1',N'TRUNG BINH',N'CON NGỰA',N'VIỆT NAM','TG02','2022','100');
SELECT * FROM SACHDUOCMUON

INSERT INTO TACGIA(MATACGIA,HOTEN,NGAYSINH,NGAYMAT,GIOITINH,NOISINH,QUEQUAN) VALUES
('TG01',N'NGÔ HIẾU HUY','1920/12/09','2016/12/02',N'NAM',N'BA BÌ',N'HIỆP HOÀ'),
('TG02',N'NGUYỄN THANH THẢO','1890/01/23','2010/02/25',N'NỮ',N'BẮC GIANG',N'BẮC GIANG');

SELECT * FROM TACGIA
DELETE FROM TACGIA

