CREATE DATABASE TEST5
IF OBJECT_ID('SINHVIEN') IS NOT NULL
DROP TABLE SINHVIEN
CREATE TABLE SINHVIEN(
    TENLOP NVARCHAR(50),
    TUOI INT,
    MSV CHAR(10) PRIMARY KEY,
    TEN NVARCHAR(50),
    DIACHI NVARCHAR(50),
    MANGANH CHAR(10),
    FOREIGN KEY(TENLOP) REFERENCES LOP(TENLOP),
    FOREIGN KEY(MANGANH) REFERENCES NGANH(MANGANH)

);
IF OBJECT_ID('LOP') IS NOT NULL
DROP TABLE LOP
CREATE TABLE LOP(
    MON NVARCHAR(10),
    SOSINHVIEN INT,
    PHONG INT,
    TENLOP NVARCHAR(50) PRIMARY KEY,

);
IF OBJECT_ID('NGANH') IS NOT NULL
DROP TABLE NGANH
CREATE TABLE NGANH(
    SOSINHVIEN INT,
    MANGANH CHAR(10) PRIMARY KEY,
    TENNGHANH NVARCHAR(50),
);

INSERT INTO SINHVIEN(TENLOP,TUOI,MANGANH,MSV,TEN,DIACHI) VALUES
(N'LOP1',18,'LAPTRINH','PH29',N'NHI',N'HANOI'),
(N'LOP2',14,'HAT','P9',N'THANH',N'TPHCM');
SELECT * FROM SINHVIEN



INSERT INTO LOP(MON, SOSINHVIEN,PHONG,TENLOP) VALUES
(N'TOAN',23,2,N'LOP1'),
(N'VAN',22,4,N'LOP2');
SELECT * FROM LOP

INSERT INTO NGANH(SOSINHVIEN,MANGANH,TENNGHANH) VALUES
(23,'LAPTRINH',N'THIETKE'),
(22,'HAT',N'CASI');
SELECT * FROM NGANH

