CREATE DATABASE TEST1
IF OBJECT_ID('SINHVIEN') IS NOT NULL
DROP TABLE SINHVIEN
CREATE TABLE SINHVIEN(
    TENLOP NVARCHAR(50),
    TUOI INT,
    MSV CHAR(10) PRIMARY KEY,
    TEN NVARCHAR(50),
    DIACHI NVARCHAR(50),
    MANGANH CHAR(10),
    FOREIGN KEY (TENLOP) REFERENCES LOP(TENLOP),
    FOREIGN KEY (MANGANH) REFERENCES NGANH(MANGANH)

   
);
IF OBJECT_ID('LOP') IS NOT NULL
DROP TABLE LOP
CREATE TABLE LOP(
    MON NVARCHAR(10),
    SOSINHVIEN INT,
    PHONG INT,
    TENLOP NVARCHAR(50) PRIMARY KEY,

);

IF OBJECT_ID('NGANH') IS NOT NULL
DROP TABLE NGANH
CREATE TABLE NGANH(
    SOSINHVIEN INT,
    MANGANH CHAR(10) PRIMARY KEY,
    TENNGHANH NVARCHAR(50),
);

