CREATE DATABASE TEST

IF OBJECT_ID('MATHANG') IS NOT NULL
DROP TABLE MATHANG
CREATE TABLE MATHANG(
    MSMH VARCHAR(50) PRIMARY KEY,
    TENHANG NVARCHAR(50),
    DONGIA VARCHAR(50),
    DONVITIEN NVARCHAR(50),


);

IF OBJECT_ID('KHACHHANG') IS NOT NULL
DROP TABLE KHACHHANG
CREATE TABLE KHACHHANG(
    MAKH VARCHAR(50) PRIMARY KEY,
    TENKH NVARCHAR(50),
    DIACHI NVARCHAR(50),


);

IF OBJECT_ID('PHIEUNHAP') IS  NOT NULL
DROP TABLE PHIEUNHAP
CREATE TABLE PHIEUNHAP(
    SOPN INT PRIMARY KEY,
    NGAYLAP DATE,
    MAKH VARCHAR(50),
    KHO VARCHAR(50),

    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
);

IF OBJECT_ID('CTNHAP') IS NOT NULL
DROP TABLE CTNHAP
CREATE TABLE CTNHAP(
    SOPN INT,
    MSMH VARCHAR(50),
    SOLUONG INT,
    PRIMARY KEY (SOPN,MSMH),

    FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP(SOPN),
    FOREIGN KEY (MSMH) REFERENCES MATHANG(MSMH),
);

INSERT INTO MATHANG(MSMH,TENHANG,DONGIA,DONVITIEN) VALUES
('01',N'SỮA','100',N'ĐỒNG'),
('02',N'NƯỚC','200',N'ĐÔ LA'),
('03',N'KẸO','300',N'TRĂM');
SELECT * FROM MATHANG


INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI) VALUES
('PH29',N'PHẠM THỊ YẾN',N'BẮC GIANG'),
('PH28',N'NGUYỄN VĂN ',N'HÀ NỘI'),
('PH27',N'PHẠM VĂN ĐỒNG',N'HIỆP HOÀ');
SELECT * FROM KHACHHANG

INSERT INTO PHIEUNHAP(SOPN,NGAYLAP,MAKH,KHO) VALUES
('1','2003/12/08','PH29','KHO1'),
('2','2013/12/08','PH28','KHO2'),
('3','2000/09/08','PH27','KHO3');
SELECT * FROM PHIEUNHAP


INSERT INTO CTNHAP(SOPN,MSMH,SOLUONG) VALUES
('1','01','9'),
('2','02','10'),
('3','03','11');
SELECT * FROM CTNHAP
---CÂU 1
SELECT CTNHAP.SOPN,TENKH,NGAYLAP, SUM(SOLUONG * DONGIA) THANHTIEN FROM CTNHAP JOIN PHIEUNHAP ON CTNHAP.SOPN = PHIEUNHAP.SOPN
JOIN KHACHHANG ON PHIEUNHAP.MAKH = KHACHHANG.MAKH
JOIN MATHANG ON MATHANG.MSMH = CTNHAP.MSMH
WHERE YEAR(NGAYLAP) > 2003
GROUP BY CTNHAP.SOPN,TENKH,NGAYLAP

---CÂU 2
SELECT TENKH,NGAYLAP,SUM(SOLUONG * DONGIA) TONGMATHANG FROM KHACHHANG JOIN PHIEUNHAP ON KHACHHANG.MAKH = PHIEUNHAP.MAKH
JOIN CTNHAP ON CTNHAP.SOPN = PHIEUNHAP.SOPN
JOIN MATHANG ON MATHANG.MSMH = CTNHAP.MSMH
WHERE YEAR(NGAYLAP) = '2003' AND MONTH(NGAYLAP) = '12'
GROUP BY TENKH,NGAYLAP

--CÂU 3
SELECT TENKH,KHACHHANG.MAKH,SUM(SOLUONG * DONGIA) TONGPHIEU FROM KHACHHANG JOIN PHIEUNHAP ON KHACHHANG.MAKH = PHIEUNHAP.MAKH
JOIN CTNHAP ON CTNHAP.SOPN = PHIEUNHAP.SOPN
JOIN MATHANG ON MATHANG.MSMH = CTNHAP.MSMH
GROUP BY TENKH,KHACHHANG.MAKH
HAVING  SUM(SOLUONG * DONGIA) > 500

---CÂU 4
SELECT KHACHHANG.MAKH,TENKH,PHIEUNHAP.SOPN,KHACHHANG.MAKH,SOLUONG,DONGIA FROM KHACHHANG JOIN PHIEUNHAP ON  PHIEUNHAP.MAKH = KHACHHANG.MAKH
JOIN CTNHAP ON CTNHAP.SOPN = PHIEUNHAP.SOPN
JOIN MATHANG ON MATHANG.MSMH = CTNHAP.MSMH
WHERE TENKH = N'PHẠM THỊ YẾN'
GROUP BY KHACHHANG.MAKH,TENKH,PHIEUNHAP.SOPN,KHACHHANG.MAKH,SOLUONG,DONGIA
 
