CREATE DATABASE DETEST

IF OBJECT_ID('THUOC') IS NOT NULL
DROP TABLE THUOC
CREATE TABLE THUOC(
    MATHUOC VARCHAR(50) PRIMARY KEY,
    TENTHUOC NVARCHAR(50),
    DONVITINH NVARCHAR(50),
    GIA INT,
    NHOMDIEUTRI NVARCHAR(50),
    
);

IF OBJECT_ID('HOSO') IS NOT NULL
DROP TABLE HOSO
CREATE TABLE HOSO(
   MAHS VARCHAR(50) PRIMARY KEY,
   HOTEN NVARCHAR(50),
   NGAYSINH DATE,
   GIOITINH NVARCHAR(50),
   CANCUOC INT,
   NGAYLAP DATE,
);


IF OBJECT_ID('KHAMBENH') IS NOT NULL
DROP TABLE KHANHBENH
CREATE TABLE KHANHBENH(
   MAKB VARCHAR(50) PRIMARY KEY,
   MAHS VARCHAR(50),
   NGAYKHAM DATE,
   BACSI NVARCHAR(50),
   KETLUON NVARCHAR(50),

   FOREIGN KEY (MAHS) REFERENCES HOSO(MAHS),
       
);


IF OBJECT_ID('TOATHUOC') IS NOT NULL
DROP TABLE TOATHUOC
CREATE TABLE TOATHUOC(
    MAKB VARCHAR(50),
    MATHUOC VARCHAR(50),
    SOLUONG INT,

    PRIMARY KEY(MAKB,MATHUOC),

    FOREIGN KEY (MATHUOC) REFERENCES THUOC(MATHUOC),
    FOREIGN KEY (MAKB) REFERENCES KHAMBENH(MAKB),  

);




