CREATE DATABASE THISINHVIEN

IF OBJECT_ID('VANPHONG') IS NOT NULL
DROP TABLE VANPHONG
CREATE TABLE VANPHONG(
    MAVP VARCHAR(50) PRIMARY KEY,
    TENVP NVARCHAR(50),
);

IF OBJECT_ID('NHANVIEN') IS NOT NULL
DROP TABLE NHANVIEN
CREATE TABLE NHANVIEN(
    MASV VARCHAR(50) PRIMARY KEY,
    HOTEN NVARCHAR(50),
    NGAYSINH DATE,
    GIOITINH NVARCHAR(50),
    MAVP VARCHAR(50),
    EMAIL NVARCHAR(50),
    SDT VARCHAR(50),
);


IF OBJECT_ID('THANNHAN') IS NOT NULL
DROP TABLE THANNHAN
CREATE TABLE THANNHAN(
    MATN VARCHAR(50),
    HOTENTN NVARCHAR(50),
    NGAYSINHTN DATE,
    MOILH NVARCHAR(50),
    MANV VARCHAR(50),

    PRIMARY KEY (MATN,MANV),

    FOREIGN KEY 
);