CREATE DATABASE QUANLYTHUEXE
IF OBJECT_ID('KHACHHANG') IS NOT NULL
DROP TABLE KHACHHANG
CREATE TABLE KHACHHANG(
    MAKHACH VARCHAR(10) PRIMARY KEY,
    HOTEN NVARCHAR(50),
    DIACHI NVARCHAR(50),
    SDT NVARCHAR(10),
    SOCANGOI NVARCHAR(20),

);

IF OBJECT_ID('THUEXE') IS NOT NULL
DROP TABLE THUEXE
CREATE TABLE THUEXE(
    MAKHACH VARCHAR(10) REFERENCES KHACHHANG(MAKHACH),
    BIENSO VARCHAR(10) REFERENCES XE(BIENSO),
    NGAYTHUE DATE,
    NGAYTRA DATE,
PRIMARY KEY (MAKHACH,BIENSO,NGAYTHUE),

);


IF OBJECT_ID('XE') IS NOT NULL
DROP TABLE XE
CREATE TABLE XE(
   BIENSO VARCHAR(10) PRIMARY KEY,
   SOGHE INT,
   DONGIA INT,
   HANGXE VARCHAR(10),

);


INSERT INTO KHACHHANG(MAKHACH,HOTEN,DIACHI,SDT,SOCANGOI) VALUES
('PH29053',N'PHẠM THỊ YẾN',N'162-HÀ DUY PHIÊN','0976198642','0834244343'),
('KH122',N'LÊ HỒNG ĐĂNG',N'10-LÊ TRỌNG TẤN','0988845633','003647000282'),
('KH123',N'TRẦN VĂN THUỶ',N'27-HOÀNG HOA THÁM','0982345612','013634005567');
SELECT * FROM KHACHHANG



INSERT INTO THUEXE(MAKHACH,BIENSO,NGAYTHUE,NGAYTRA) VALUES
('KH122','29N-2221','2022/03/20','2022/03/25'),
('KH122','29N-2221','2022/01/10','2022/01/12'),
('KH123','29H-1234','2021/03/18','2021/03/18');
SELECT * FROM THUEXE
DELETE FROM THUEXE



INSERT INTO XE(BIENSO,SOGHE,DONGIA,HANGXE) VALUES
('29H-1234','50','500','TOYOTA'),
('29N-2221','7','200','HONDA'),
('29A-1432','29','350','FORD');
SELECT * FROM XE
DELETE FROM XE

/*2A. Tìm tất cả các khách thuê có họ là ‘Lê’. */
SELECT HOTEN FROM KHACHHANG WHERE HOTEN LIKE  N'LÊ%'
/*2B. Tìm tất cả các khách có số điện thoại của Nhà Mạng ‘Việt Tell’. */
SELECT SDT FROM KHACHHANG WHERE SDT  LIKE '09%' OR SDT  LIKE '08%'

/*2C. Tìm tất cả các xe có đơn giá đắt nhất của hãng Ford.*/
SELECT HANGXE,BIENSO,MAX(DONGIA) DONGIA FROM XE WHERE HANGXE = 'FORD' GROUP BY HANGXE,BIENSO
SELECT * FROM XE



/*2D. . Đưa ra tất cả họ tên khách,số ngày thuê,  số tiền thuê xe của các khách trong tháng 3/2022. // datediff(day,ngaythue,ngaytra) = so ngay thue.*/
SELECT HOTEN, DATEDIFF(DAY, NGAYTHUE, NGAYTRA) AS SONGAYTHUE, DATEDIFF(DAY, NGAYTHUE, NGAYTRA)*DONGIA AS SOTIENTHUE
FROM KHACHHANG JOIN THUEXE ON KHACHHANG.MAKHACH=THUEXE.MAKHACH
JOIN Xe ON Xe.BIENSO=THUEXE.BIENSO
WHERE MONTH(NGAYTHUE)='3'AND YEAR(NGAYTHUE)='2022'

/*2E.. Đưa ra thông tin khách thuê xe nhiều lần nhất. */

/*2F. Đưa ra số lượt được thuê của mỗi xe.   . */
SELECT BIENSO, COUNT(MAKHACH) FROM THUEXE GROUP BY BIENSO

/*2G... Tính tổng tiền thu được từ mỗi đầu xe.  */

/*2H.. Đưa ra đầu xe được thuê ít nhất.. */
/*3A.Giảm đơn giá 20% cho các xe  trên 20 chỗ. */
UPDATE XE
SET DONGIA  = DONGIA * 0.8
WHERE SOGHE > 20
SELECT * FROM XE

/*3B.Xóa các thông tin thuê xe trước năm 2022 */
DELETE FROM THUEXE WHERE YEAR(NGAYTHUE) < 2022
SELECT * FROM THUEXE
