CREATE DATABASE BENHVIEN
IF OBJECT_ID('ORDERS') IS NOT NULL
DROP TABLE ORDERS
CREATE TABLE ORDERS(
    ORDERID INT,
    CUSTOMERID INT,
    ORDERDATE DATETIME,
    
);

IF OBJECT_ID('CUSTOMERS') IS NOT NULL
DROP TABLE CUSTOMERS
CREATE TABLE CUSTOMERS(
    CUSTOMERID INT,
    CUSTOMERNAME NVARCHAR(30),
    CONTACTNAME NVARCHAR(30),
    COUNTRY NVARCHAR(30),
);

INSERT INTO ORDERS(ORDERID,CUSTOMERID,ORDERDATE) VALUES
('10308','2','1996/09/18'),
('10309','37','1996/09/19'),
('103010','77','1996/09/20');
SELECT * FROM ORDERS

INSERT INTO CUSTOMERS(CUSTOMERID,CUSTOMERNAME,CONTACTNAME,COUNTRY) VALUES
('1',N'NGỌC','PHN',N'VIỆT NAM'),
('2',N'THANH','PTT',N'MỸ');
SELECT * FROM CUSTOMERS


ALTER TABLE ORDERS  --- CHEN THEM 1 COT VAO BANG
ADD PAYMENTTYPE NVARCHAR(40);

ALTER TABLE ORDERS
ADD ORDERSSTATUS NVARCHAR(40);--- CHEN THEM 1 COT VAO BANG



----THÊM DỮ LIỆU VÀO CHO BẢNG PAYMENTTYPE VÀ ORDERSSTATUS
UPDATE ORDERS
SET PAYMENTTYPE = N'CHUYỂN KHOẢN', ORDERSSTATUS = N'THÀNH CÔNG'
WHERE ORDERID = 10308;


UPDATE ORDERS
SET PAYMENTTYPE = N'TIỀN MẶT' ,  ORDERSSTATUS = N'KHÔNG THÀNH CÔNG'
WHERE ORDERID = 10309;

UPDATE ORDERS
SET PAYMENTTYPE = N'CHUYỂN KHOẢN', ORDERSSTATUS  = N'THÀNH CÔNG'
WHERE ORDERID = 103010;


-----JOIN

SELECT ORDERS.ORDERID, ORDERS.ORDERSSTATUS,CUSTOMERS.CONTACTNAME,CUSTOMERS.CUSTOMERNAME,CUSTOMERS.COUNTRY
FROM ORDERS
FULL JOIN CUSTOMERS ON ORDERS.CUSTOMERID = CUSTOMERS.CUSTOMERID;