CREATE DATABASE PHUONG_LAB8


IF OBJECT_ID('THUOC') IS NOT NULL
DROP TABLE THUOC
CREATE TABLE THUOC(
MAT CHAR(10),
TENTHUOC NVARCHAR(50),
DONVITINH NVARCHAR(50),
GIA INT CHECK(GIA>=0),
NHOMDIEUCHI NVARCHAR(50),
PRIMARY KEY (MAT)
);

IF OBJECT_ID('HOSO') IS NOT NULL
DROP TABLE HOSO
CREATE TABLE HOSO(
MAHS CHAR(10),
HOTEN NVARCHAR(50),
NGAYSINH DATE,
GIOITINH NVARCHAR(15),
CANCUOC VARCHAR(20),
NGAYLAP DATE,
PRIMARY KEY (MAHS)
);

IF OBJECT_ID('KHAMBENH') IS NOT NULL
DROP TABLE KHAMBENH
CREATE TABLE KHAMBENH(
MAKB CHAR(10),
MAHS CHAR(10),
NGAYKHAM DATE,
BACSI NVARCHAR(50),
KETLUAN NVARCHAR(50),
PRIMARY KEY (MAKB),
FOREIGN KEY (MAHS) REFERENCES HOSO(MAHS)
);

IF OBJECT_ID('TOATHUOC') IS NOT NULL
DROP TABLE TOATHUOC
CREATE TABLE TOATHUOC(
MAKB CHAR(10),
MAT CHAR(10),
SOLUONG INT CHECK(SOLUONG >= 0),
PRIMARY KEY (MAKB,MAT),
FOREIGN KEY (MAKB) REFERENCES KHAMBENH(MAKB),
FOREIGN KEY (MAT) REFERENCES THUOC(MAT)
);

INSERT INTO THUOC(MAT,TENTHUOC, DONVITINH, GIA, NHOMDIEUCHI) VALUES
('T01', N'B?T', N'GAM', 60000, N'TH?N'),
('T02', N'TI�N', N'GAM', 140000, N'?AU B?NG'),
('T03', N'TI?N', N'GAM', 30000, N'NGH�O');


INSERT INTO HOSO(MAHS,HOTEN, NGAYSINH, GIOITINH, CANCUOC, NGAYLAP) VALUES
('HS01', N'TR?N TH? THU PH??NG', '2003/08/09', N'N?', '40G120304163', '2005/04/02'),
('HS02', N'TH?T L� ??P', '2002/01/12', N'NAM', '00D20041630', '2009/04/21'),
('HS03', N'NGUY?N THU TH?Y', '1997/03/22', N'N?', 'N0932311630', '2009/09/03');

INSERT INTO KHAMBENH(MAKB,MAHS, NGAYKHAM, BACSI, KETLUAN) VALUES 
('KB01', 'HS01', '2012/02/18', N'KH�NG BI?T AI', N'?N'),
('KB02', 'HS02', '2014/04/22', N'XU�N THU TH?Y', N'UNG TH?'),
('KB03', 'HS03', '2020/12/04', N'TR?N TOANG R?I', N'S?P CH?T');

INSERT INTO TOATHUOC(MAKB,MAT, SOLUONG) VALUES 
('KB01', 'T01', 4),
('KB02', 'T02', 9),
('KB03', 'T03', 12);
--1
SELECT TT.MAT, TENTHUOC, SOLUONG FROM THUOC AS T JOIN TOATHUOC AS TT 
ON T.MAT = TT.MAT JOIN KHAMBENH AS KB ON TT.MAKB = KB.MAKB
WHERE MAHS LIKE '%03'
--2
SELECT HS.MAHS, HOTEN, YEAR(GETDATE()) - YEAR(NGAYSINH) AS 'TUOI' FROM HOSO AS HS
JOIN KHAMBENH AS KB ON HS.MAHS=KB.MAHS
WHERE KB.NGAYKHAM = '2014/04/22'
ORDER BY HS.MAHS DESC
--3

--4
SELECT * FROM THUOC
WHERE NHOMDIEUCHI LIKE N'TH?N' AND  GIA >=50000 AND GIA <=100000
--5
SELECT KB.NGAYKHAM,KB.BACSI,KB.KETLUAN FROM KHAMBENH AS KB
JOIN HOSO AS HS ON KB.MAHS=HS.MAHS
WHERE YEAR(HS.NGAYSINH) = '2003'
--10
UPDATE THUOC SET GIA= GIA * 0.9
WHERE NHOMDIEUCHI LIKE N'NGH�O'
--11
DELETE FROM TOATHUOC
WHERE MAKB LIKE 'KB01%' OR MAKB LIKE 'KB05%'
--12
DELETE FROM THUOC
WHERE GIA > 100000
